{% set name = "conda-prefix-replacement" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: c4387bd35e286b3fe30b16e325a371f1cad8814cb06a356b5967ac6a3b12c9ad

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - cpr = cpr.cli:cli

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - six
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - cpr
  commands:
    - cpr -V

about:
  home: http://github.com/conda/conda-prefix-replacement
  license: BSD-3
  license_family: BSD
  license_file: LICENSE
  summary: Detect and replace prefix paths embedded in files

extra:
  recipe-maintainers:
    - msarahan
